version: "3"

vars:
  APP: apimoex
  TESTS: tests
  TOOLS: go-task uv

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  install:
    desc: Setup venv, install tools and dependencies
    cmds:
      - brew install {{.TOOLS}}
      - uv sync --frozen

  update:
    desc: Upgrade tools and dependencies
    cmds:
      - brew upgrade {{.TOOLS}}
      - uv sync --upgrade

  lint:
    desc: Format and lint
    cmds:
      - uv run ruff format {{.APP}} --check
      - uv run ruff format {{.TESTS}} --check
      - uv run ruff check {{.APP}} --unsafe-fixes --exit-non-zero-on-fix
      - uv run ruff check {{.TESTS}} --unsafe-fixes --exit-non-zero-on-fix
      - uv run pyright {{.APP}}

  test:
    desc: Lint and test
    deps: [lint]
    cmds:
      - uv run pytest {{.TESTS}} --cov={{.APP}}

  docs:
    desc: Update html docs
    cmds:
      - uv run sphinx-build -M html docs docs/build

  publish:
    desc: Publish to pypi
    deps: [lint, docs]
    cmds:
      - uv build --clear
      - uv publish --token {{.CLI_ARGS}}
