name: tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: macos-latest

    steps:
      - name: Checkout aiomoex
        uses: actions/checkout@v3

      - name: Install go-task
        run: brew install go-task

      - name: Setup venv, install tools and dependencies
        run: task install

      - name: Lint and test
        run: task test
